// <auto-generated />
using System;
using FinanceApplicationAPI.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanceApplicationAPI.DB
{
    [DbContext(typeof(APIDBContext))]
    [Migration("20230115204719_creation")]
    partial class creation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("FinanceApplicationAPI.Data.Models.Transaction", b =>
                {
                    b.Property<string>("TransactionID")
                        .HasMaxLength(36)
                        .HasColumnType("varchar")
                        .HasColumnName("ID");

                    b.Property<string>("AccountID")
                        .HasMaxLength(36)
                        .HasColumnType("varchar")
                        .HasColumnName("AccountID");

                    b.Property<double>("Amount")
                        .HasMaxLength(20)
                        .HasColumnType("integer")
                        .HasColumnName("Amount");

                    b.Property<DateTime>("Date")
                        .HasMaxLength(50)
                        .HasColumnType("datetime")
                        .HasColumnName("Date");

                    b.Property<bool>("FlowType")
                        .HasMaxLength(1)
                        .HasColumnType("integer")
                        .HasColumnName("FlowType");

                    b.Property<string>("TransactionNameID")
                        .HasMaxLength(36)
                        .HasColumnType("varchar")
                        .HasColumnName("TransactionNameID");

                    b.Property<string>("TransactionTypeID")
                        .HasMaxLength(36)
                        .HasColumnType("varchar")
                        .HasColumnName("TransactionTypeID");

                    b.HasKey("TransactionID");

                    b.HasIndex("AccountID");

                    b.HasIndex("TransactionNameID");

                    b.HasIndex("TransactionTypeID");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("FinanceApplicationAPI.DataAccess.Models.Account", b =>
                {
                    b.Property<string>("AccountID")
                        .HasMaxLength(36)
                        .HasColumnType("varchar")
                        .HasColumnName("ID");

                    b.Property<string>("AccountName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("UserName");

                    b.HasKey("AccountID");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("FinanceApplicationAPI.DataAccess.Models.TransactionName", b =>
                {
                    b.Property<string>("TransactionNameID")
                        .HasMaxLength(36)
                        .HasColumnType("varchar")
                        .HasColumnName("ID");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("Name");

                    b.HasKey("TransactionNameID");

                    b.ToTable("TransactionName", (string)null);
                });

            modelBuilder.Entity("FinanceApplicationAPI.DataAccess.Models.TransactionType", b =>
                {
                    b.Property<string>("TransactionTypeID")
                        .HasMaxLength(36)
                        .HasColumnType("varchar")
                        .HasColumnName("ID");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("Type");

                    b.HasKey("TransactionTypeID");

                    b.ToTable("TransactionType", (string)null);
                });

            modelBuilder.Entity("FinanceApplicationAPI.Data.Models.Transaction", b =>
                {
                    b.HasOne("FinanceApplicationAPI.DataAccess.Models.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Account_Transactions");

                    b.HasOne("FinanceApplicationAPI.DataAccess.Models.TransactionName", "TransactionName")
                        .WithMany("Transactions")
                        .HasForeignKey("TransactionNameID")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Transaction_Name");

                    b.HasOne("FinanceApplicationAPI.DataAccess.Models.TransactionType", "TransactionType")
                        .WithMany("Transactions")
                        .HasForeignKey("TransactionTypeID")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Transaction_Type");

                    b.Navigation("Account");

                    b.Navigation("TransactionName");

                    b.Navigation("TransactionType");
                });

            modelBuilder.Entity("FinanceApplicationAPI.DataAccess.Models.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FinanceApplicationAPI.DataAccess.Models.TransactionName", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FinanceApplicationAPI.DataAccess.Models.TransactionType", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
