// <auto-generated />
using System;
using FinanceApplicationAPI.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanceApplicationAPI.DB
{
    [DbContext(typeof(APIDBContext))]
    [Migration("20230115122116_creation")]
    partial class creation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("FinanceApplicationAPI.Data.Models.Transaction", b =>
                {
                    b.Property<string>("TransactionID")
                        .HasMaxLength(36)
                        .HasColumnType("varchar")
                        .HasColumnName("TransactionID");

                    b.Property<string>("AccountID")
                        .HasMaxLength(36)
                        .HasColumnType("varchar")
                        .HasColumnName("AccountID");

                    b.Property<double>("Amount")
                        .HasMaxLength(20)
                        .HasColumnType("integer")
                        .HasColumnName("Amount");

                    b.Property<DateTime>("Date")
                        .HasMaxLength(50)
                        .HasColumnType("datetime")
                        .HasColumnName("Date");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("Description");

                    b.Property<bool>("TransactionType")
                        .HasMaxLength(1)
                        .HasColumnType("integer")
                        .HasColumnName("TransactionType");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("Type");

                    b.HasKey("TransactionID");

                    b.HasIndex("AccountID");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("FinanceApplicationAPI.DataAccess.Models.Account", b =>
                {
                    b.Property<string>("AccountID")
                        .HasMaxLength(36)
                        .HasColumnType("varchar")
                        .HasColumnName("AccountID");

                    b.Property<string>("AccountName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("UserName");

                    b.HasKey("AccountID");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("FinanceApplicationAPI.Data.Models.Transaction", b =>
                {
                    b.HasOne("FinanceApplicationAPI.DataAccess.Models.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountID")
                        .HasConstraintName("FK_Account_Transactions");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("FinanceApplicationAPI.DataAccess.Models.Account", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
