// <auto-generated />
using System;
using FinanceApplicationAPI.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanceApplicationAPI.DB
{
    [DbContext(typeof(APIDBContext))]
    partial class APIDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("FinanceApplicationAPI.Data.Models.Transaction", b =>
                {
                    b.Property<string>("TransactionID")
                        .HasMaxLength(36)
                        .HasColumnType("varchar")
                        .HasColumnName("TransactionID");

                    b.Property<double>("Amount")
                        .HasMaxLength(20)
                        .HasColumnType("integer")
                        .HasColumnName("Amount");

                    b.Property<DateTime>("Date")
                        .HasMaxLength(50)
                        .HasColumnType("datetime")
                        .HasColumnName("Date");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("Description");

                    b.Property<bool>("TransactionType")
                        .HasMaxLength(1)
                        .HasColumnType("integer")
                        .HasColumnName("TransactionType");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("Type");

                    b.Property<string>("UserID")
                        .HasMaxLength(36)
                        .HasColumnType("varchar")
                        .HasColumnName("UserID");

                    b.HasKey("TransactionID");

                    b.HasIndex("UserID");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("FinanceApplicationAPI.DataAccess.Models.Account", b =>
                {
                    b.Property<string>("AccountID")
                        .HasMaxLength(36)
                        .HasColumnType("varchar")
                        .HasColumnName("UserID");

                    b.Property<string>("AccountName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("UserName");

                    b.HasKey("AccountID");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("FinanceApplicationAPI.Data.Models.Transaction", b =>
                {
                    b.HasOne("FinanceApplicationAPI.DataAccess.Models.Account", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserID")
                        .HasConstraintName("FK_User_Transactions");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinanceApplicationAPI.DataAccess.Models.Account", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
